spring.application.name=EcommerceApp
server.port=7078

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Tata@123
spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceApp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true


#Multipart Configuartion


#Enables Multipart uploads
